//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToguisModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_AUTHENTICATION_TYPE
    {
        public TG_AUTHENTICATION_TYPE()
        {
            this.TG_USER = new HashSet<TG_USER>();
        }
    
        public int AUTH_ID { get; set; }
        public string AUTH_NAME { get; set; }
    
        public virtual ICollection<TG_USER> TG_USER { get; set; }
    }
}
