//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToguisModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_COMMENTS
    {
        public int COM_ID { get; set; }
        public string USR_ID { get; set; }
        public string COM_COMMENT { get; set; }
        public int POI_ID { get; set; }
        public System.DateTime COM_DATE { get; set; }
    
        public virtual TG_USER TG_USER { get; set; }
    }
}
