//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToguisModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_CITY
    {
        public TG_CITY()
        {
            this.TG_INTEREST_POINT = new HashSet<TG_INTEREST_POINT>();
        }
    
        public int CITY_ID { get; set; }
        public Nullable<int> STE_ID { get; set; }
        public string CITY_NAME { get; set; }
        public int CITY_WOEID { get; set; }
    
        public virtual TG_STATE TG_STATE { get; set; }
        public virtual ICollection<TG_INTEREST_POINT> TG_INTEREST_POINT { get; set; }
    }
}
