//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToguisModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class TG_INTEREST_POINT
    {
        public TG_INTEREST_POINT()
        {
            this.TG_POI_DESCRIPTION = new HashSet<TG_POI_DESCRIPTION>();
            this.TG_POI_USER_DATA = new HashSet<TG_POI_USER_DATA>();
        }
    
        public int POI_ID { get; set; }
        public int PTYP_ID { get; set; }
        public string POI_IMAGE_PATH { get; set; }
        public double POI_LATITUDE { get; set; }
        public double POI_LONGITUDE { get; set; }
        public double POI_ALTITUDE { get; set; }
        public string POI_ADDRESS { get; set; }
        public int CITY_ID { get; set; }

        [NotMapped]
        public float RATING { get; set; }

        public virtual TG_POI_TYPE TG_POI_TYPE { get; set; }
        public virtual ICollection<TG_POI_DESCRIPTION> TG_POI_DESCRIPTION { get; set; }
        public virtual ICollection<TG_POI_USER_DATA> TG_POI_USER_DATA { get; set; }
        public virtual TG_CITY TG_CITY { get; set; }
    }
}
