//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToguisModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_POI_USER_DATA
    {
        public string USR_ID { get; set; }
        public int POI_ID { get; set; }
        public Nullable<double> UDAT_RATING { get; set; }
        public bool UDAT_FAVORITE { get; set; }
        public bool UDAT_VISITED { get; set; }
    
        public virtual TG_INTEREST_POINT TG_INTEREST_POINT { get; set; }
        public virtual TG_USER TG_USER { get; set; }
    }
}
