//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToguisModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_POI_DESCRIPTION
    {
        public int POI_ID { get; set; }
        public int LNG_ID { get; set; }
        public string POID_NAME { get; set; }
        public string POID_DESCRIPTION { get; set; }
    
        public virtual TG_INTEREST_POINT TG_INTEREST_POINT { get; set; }
        public virtual TG_LANGUAGE TG_LANGUAGE { get; set; }
    }
}
