//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToguisModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_STATE
    {
        public TG_STATE()
        {
            this.TG_CITY = new HashSet<TG_CITY>();
        }
    
        public int STE_ID { get; set; }
        public Nullable<int> CTR_ID { get; set; }
        public string STE_NAME { get; set; }
    
        public virtual ICollection<TG_CITY> TG_CITY { get; set; }
        public virtual TG_COUNTRY TG_COUNTRY { get; set; }
    }
}
