//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToguisModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToguisEntities : DbContext
    {
        public ToguisEntities()
            : base("name=ToguisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TG_AUTHENTICATION_TYPE> TG_AUTHENTICATION_TYPE { get; set; }
        public DbSet<TG_GENDER> TG_GENDER { get; set; }
        public DbSet<TG_ROLE> TG_ROLE { get; set; }
        public DbSet<TG_USER> TG_USER { get; set; }
        public DbSet<TG_TEMPORAL_RECOVERY> TG_TEMPORAL_RECOVERY { get; set; }
    }
}
